export const AppLabels = {
  brand: {
    name: 'Abihani',
    tagline: 'The social marketplace',
    legalFooter: 'Abihani is a product of Abihani Express, registered in Nigeria.',
  },
  auth: {
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    continueButton: 'Continue',
    ageGate: 'By continuing, you confirm you are 18 or older.',
    termsConsent: 'By continuing, you agree to our Terms and Privacy Policy.',
    countryLabel: 'Country',
    countryFixed: 'Nigeria (+234)',
    otpHeading: 'Check your email',
    otpSubheading: 'Enter the 6-digit code sent to your inbox',
    otpPlaceholder: '000000',
    recoveryHeading: 'Your recovery code',
    recoverySubheading: 'Save this 8-digit code. It is shown once and is your last door into this account.',
    recoveryConfirm: 'I saved my recovery code',
    resendCode: 'Resend code',
    oneTapLogin: 'Log in',
  },
  feed: {
    forYouTab: 'For You',
    followingTab: 'Following',
    buyNow: 'Buy now',
    shipsFrom: 'Ships from',
    inStock: 'In stock',
    soldOut: 'Sold out',
    emptyFeed: 'Nothing here yet.',
    emptyFollowing: 'No posts from accounts you follow yet.',
    doubleTapToLike: 'Double-tap to like',
    officialNotice: 'Official Notice',
    dismissNotice: 'Swipe to dismiss',
  },
  create: {
    screenTitle: 'New Post',
    mediaPickerPrompt: 'Add photos or a video.',
    mediaPickerPartial: (count: number) => `Add more photos (${count}/5).`,
    overLimitPhotos: (count: number) => `Up to 5 photos. You selected ${count}.`,
    overLimitVideo: 'One video per post.',
    mixedMediaError: 'Never mix photos and video in the same post.',
    captionPlaceholder: 'Describe what you are selling or sharing...',
    priceLabel: 'Price (optional)',
    pricePlaceholder: '₦0',
    stockLabel: 'Stock quantity (optional)',
    stockPlaceholder: '1',
    shipFromLabel: 'Ships from',
    hashtagsLabel: 'Hashtags (required)',
    hashtagsPlaceholder: '#fashion #abuja #handmade',
    hashtagsMissingError: 'At least one hashtag is required to classify your post.',
    noPayoutWarning: 'Add a payout method to sell. Takes 2 minutes.',
    publishButton: 'Publish',
  },
  orders: {
    listTitle: 'Orders',
    emptyOrders: 'No orders yet.',
    buySheetTitle: 'Complete payment',
    directPaymentDisclaimer:
      'Pay the seller directly. Abihani does not hold your money yet. Pay only after you trust this seller.',
    iHavePaid: 'I have paid',
    askAboutThisFirst: 'Ask about this first',
    sellerAccountDetails: 'Seller Bank Details',
    bankName: 'Bank',
    accountNumber: 'Account Number',
    accountName: 'Account Name',
    amountDue: 'Amount Due',
    buyerNoteLabel: 'Order Note (captured upon payment)',
    buyerNotePlaceholder: 'Delivery address, preferred contact, or special request...',
    buyerContactPhoneLabel: 'Contact Phone',
    buyerContactPhonePlaceholder: '08012345678',
    statuses: {
      paidUnconfirmed: 'Paid (Unconfirmed)',
      paidReceiptUploaded: 'Paid (Receipt Uploaded)',
      paidConfirmed: 'Paid (Confirmed)',
      shipped: 'Shipped',
      done: 'Done',
      cancelled: 'Cancelled',
      disputed: 'Disputed',
    },
    actions: {
      uploadReceipt: 'Upload receipt',
      askForReceipt: 'Ask for receipt',
      shipAnyway: 'Ship anyway',
      confirmReceived: 'Confirm delivery received',
      confirmMoneyReceived: 'Yes, money arrived',
      cancelOrder: 'Cancel order',
      openDispute: 'Open dispute',
      contactSeller: 'Contact seller',
      contactBuyer: 'Contact buyer',
    },
    receiptBadge: 'Receipt',
    noReceiptUploaded: 'No receipt uploaded.',
    disputeNotice:
      'We cannot refund your money yet. But we can ban this seller if they are wrong. Tell us what happened.',
  },
  offers: {
    bannerTitle: 'Special Offer Available',
    sendOfferButton: 'Send an offer',
    acceptOffer: 'Accept offer',
    offerPriceLabel: 'Offer Price',
    offerAccepted: 'Offer accepted. Re-opening checkout.',
  },
  profile: {
    editProfile: 'Edit profile',
    shareProfile: 'Share',
    follow: 'Follow',
    following: 'Following',
    postsTab: 'Posts',
    likedTab: 'Liked',
    savedTab: 'Saved',
    emptyOwnPosts: 'No posts yet. Post something.',
    emptyOtherPosts: 'No posts yet.',
    trustSales: 'sales',
    trustRating: 'rating',
    trustDisputes: 'disputes',
    newSellerChip: 'New seller · 0 completed orders',
    verifiedSeller: 'Verified Seller',
  },
  settings: {
    title: 'Settings',
    accountSection: 'Account',
    sellingSection: 'Selling',
    notificationsSection: 'Notifications',
    supportSection: 'Support',
    dangerSection: 'Danger Zone',
    deliveryFees: 'Delivery fees',
    payoutMethod: 'Payout method',
    recoveryCode: 'Recovery code',
    addAccount: 'Add account',
    switchAccount: 'Switch account',
    helpSheet: 'Help & Safety',
    blockedAccounts: 'Blocked accounts',
    logOut: 'Log out',
    deleteAccount: 'Delete account',
    deleteAccountBlocked: 'Cannot delete account with open orders.',
  },
  bank: {
    chooseBank: 'Select Bank',
    accountNumber: 'NUBAN Account Number',
    verifyAccount: 'Verify account',
    confirmAndSave: 'Confirm and save',
    verifiedAccountName: 'Verified Account Name',
  },
  admin: {
    title: 'Admin Dashboard',
    masterSwitches: 'Master Switches',
    buySellSwitch: 'Buy & Sell',
    sellerDefaultSwitch: 'Seller Default',
    disputesSwitch: 'Disputes Queue',
    signupsSwitch: 'New Signups',
    metricsTitle: 'Platform Metrics',
  },
  errors: {
    generalTitle: 'Something went wrong',
    generalSubtitle: 'Try again later',
    retryButton: 'Retry',
    slowConnection: 'Slow connection. Still trying…',
    timeoutError: 'Could not load. Tap to retry.',
    offlineNotice: 'Offline Mode — Cached data is being used.',
  },
} as const;
