export const buttonLabels = {
  continue: 'Continue',
  buyNow: 'Buy now',
  buyPaused: 'Paused',
  iHavePaid: 'I have paid',
  askAboutThisFirst: 'Ask about this first',
  uploadReceipt: 'Upload receipt',
  confirmReceiptUpload: 'Confirm Receipt Upload',
  askForReceipt: 'Ask for receipt',
  shipAnyway: 'Ship anyway',
  markAsShipped: 'Mark as Shipped',
  confirmMoneyReceived: 'Yes, money arrived',
  confirmDeliveryReceived: 'Confirm delivery received',
  cancelOrder: 'Cancel order',
  openDispute: 'Open dispute',
  submitDispute: 'Submit Dispute',
  publish: 'Publish',
  publishing: 'Publishing...',
  follow: 'Follow',
  following: 'Following',
  editProfile: 'Edit profile',
  share: 'Share',
  shareMilestone: 'Share Milestone',
  cancel: 'Cancel',
  close: 'Close',
  retry: 'Retry',
  verifyAccount: 'Verify account',
  confirmAndSave: 'Confirm and save',
  claimOffer: 'Claim',
  savedRecoveryCode: 'I saved my recovery code',
  logOut: 'Log out',
  deleteAccount: 'Delete account',
  callDirectly: 'Call directly',
  openInWhatsApp: 'Open in WhatsApp',
  copyNumber: 'Copy number',
  installApp: 'Install',
  guide: 'Guide',
  clear: 'Clear',
  learnHowItWorks: 'Learn how it works',
} as const;
