export const headingLabels = {
  feed: 'Abihani',
  forYou: 'For You',
  following: 'Following',
  discover: 'Discover',
  create: 'New Post',
  orders: 'Orders',
  orderDetail: 'Order Thread',
  profile: 'Profile',
  settings: 'Settings',
  admin: 'Admin Dashboard',
  support: 'Help & Safety',
  signup: 'Welcome to Abihani',
  otpVerify: 'Enter the code',
  recoveryCode: 'Save your code',
  splash: 'Abihani',
  buySheet: 'Complete payment',
  uploadReceipt: 'Upload Payment Receipt',
  contactInfo: 'Contact Information',
  payoutMethod: 'Payout Bank Account',
  terms: 'Terms of Service',
  privacy: 'Privacy Policy',
  about: 'About Abihani',
} as const;