export const NigerianLocations = [
  'Lagos (Ikeja)',
  'Lagos (Lekki / VI)',
  'Lagos (Yaba / Surulere)',
  'Abuja (FCT)',
  'Kano (Kano Municipal)',
  'Rivers (Port Harcourt)',
  'Oyo (Ibadan)',
  'Kaduna (Kaduna Central)',
  'Enugu (Enugu Urban)',
  'Edo (Benin City)',
  'Delta (Warri / Asaba)',
  'Ogun (Abeokuta)',
  'Anambra (Onitsha)',
  'Plateau (Jos)',
] as const;
