import { UserProfile } from '../types/user.types';
import { Post, OfficialNotice } from '../types/post.types';
import { Order } from '../types/order.types';
import { CommentItem } from '../types/comment.types';

export const INITIAL_CURRENT_USER: UserProfile = {
  id: 'usr_me',
  email: 'bayeroisa2003@gmail.com',
  handle: 'bayero',
  displayName: 'Bayero Isa',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80',
  bio: 'Building Abihani. Nigerian craftsmanship, bespoke luxury & authentic street fashion.',
  location: 'Abuja (FCT)',
  contactPhone: '+2348031112233',
  isVerified: true,
  salesCount: 14,
  rating: 4.9,
  disputesCount: 0,
  followersCount: 1240,
  followingCount: 38,
  payoutMethod: {
    bankId: 'gtb',
    bankName: 'Guaranty Trust Bank (GTBank)',
    accountNumber: '0123456789',
    accountName: 'BAYERO ISA',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
  },
  canBuy: true,
  canSell: true,
  canPost: true,
  canComment: true,
  canMessage: true,
  isSuspended: false,
  isBanned: false,
  createdAt: '2026-01-10T10:00:00Z',
};

export const SELLER_AMINA: UserProfile = {
  id: 'usr_amina',
  email: 'amina.couture@abihani.ng',
  handle: 'aminacouture',
  displayName: 'Amina Bello Atelier',
  avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80',
  coverUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1000&auto=format&fit=crop&q=80',
  bio: 'Handcrafted Northern Nigerian Aso-Oke, Kaftans & Silk Turbans. Worldwide courier from Kano.',
  location: 'Kano (Kano Municipal)',
  contactPhone: '+2347067551634',
  isVerified: true,
  salesCount: 42,
  rating: 5.0,
  disputesCount: 0,
  followersCount: 3450,
  followingCount: 42,
  payoutMethod: {
    bankId: 'kuda',
    bankName: 'Kuda Microfinance Bank',
    accountNumber: '2001928374',
    accountName: 'AMINA BELLO COUTURE',
    isVerified: true,
    verifiedAt: '2026-02-01T12:00:00Z',
  },
  canBuy: true,
  canSell: true,
  canPost: true,
  canComment: true,
  canMessage: true,
  isSuspended: false,
  isBanned: false,
  createdAt: '2026-01-15T08:00:00Z',
};

export const SELLER_FEMI: UserProfile = {
  id: 'usr_femi',
  email: 'femi.leather@abihani.ng',
  handle: 'femi_crafts',
  displayName: 'Femi Leatherworks',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  coverUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1000&auto=format&fit=crop&q=80',
  bio: '100% genuine vegetable-tanned Nigerian leather boots, wallets & duffle bags. Lekki workshop.',
  location: 'Lagos (Lekki / VI)',
  contactPhone: '+2348029988776',
  isVerified: true,
  salesCount: 28,
  rating: 4.8,
  disputesCount: 0,
  followersCount: 1890,
  followingCount: 65,
  payoutMethod: {
    bankId: 'access',
    bankName: 'Access Bank',
    accountNumber: '0098765432',
    accountName: 'FEMI ADEYEMI LEATHER',
    isVerified: true,
    verifiedAt: '2026-02-10T14:30:00Z',
  },
  canBuy: true,
  canSell: true,
  canPost: true,
  canComment: true,
  canMessage: true,
  isSuspended: false,
  isBanned: false,
  createdAt: '2026-02-01T09:30:00Z',
};

export const SELLER_CHIDERA: UserProfile = {
  id: 'usr_chidera',
  email: 'chidera.gems@abihani.ng',
  handle: 'chideragems',
  displayName: 'Chidera Obi Jewelry',
  avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
  bio: 'Raw Nigerian tourmaline, sapphire & solid 18k recycled gold rings. New seller.',
  location: 'Plateau (Jos)',
  contactPhone: '+2348145566778',
  isVerified: false,
  salesCount: 2,
  disputesCount: 0,
  followersCount: 310,
  followingCount: 19,
  payoutMethod: {
    bankId: 'zenith',
    bankName: 'Zenith Bank',
    accountNumber: '1122334455',
    accountName: 'CHIDERA OBI',
    isVerified: true,
    verifiedAt: '2026-03-01T11:00:00Z',
  },
  canBuy: true,
  canSell: true,
  canPost: true,
  canComment: true,
  canMessage: true,
  isSuspended: false,
  isBanned: false,
  createdAt: '2026-03-01T10:00:00Z',
};

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_01',
    sellerId: SELLER_AMINA.id,
    seller: SELLER_AMINA,
    media: [
      {
        id: 'med_01_a',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=1080&auto=format&fit=crop&q=80',
        aspectRatio: 'vertical',
      },
      {
        id: 'med_01_b',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1080&auto=format&fit=crop&q=80',
        aspectRatio: 'vertical',
      },
    ],
    caption: 'Emerald & Gold hand-woven royal Kaftan with intricate thread embroidery on pure Kano cotton. Ships nationwide.',
    hashtags: ['#kaftan', '#handmade', '#kano', '#abihani', '#luxury'],
    price: 68000,
    stock: 4,
    shipFrom: 'Kano (Kano Municipal)',
    likesCount: 142,
    commentsCount: 19,
    sharesCount: 11,
    savesCount: 34,
    viewsCount: 1250,
    watchTimeSeconds: 180,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(), // 4h ago
  },
  {
    id: 'post_02',
    sellerId: SELLER_FEMI.id,
    seller: SELLER_FEMI,
    media: [
      {
        id: 'med_02_a',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1080&auto=format&fit=crop&q=80',
        aspectRatio: 'vertical',
      },
      {
        id: 'med_02_b',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1080&auto=format&fit=crop&q=80',
        aspectRatio: 'vertical',
      },
    ],
    caption: 'Full-grain weekend travel bag in burnished caramel leather. Hand-stitched with brass hardware built to last 20 years.',
    hashtags: ['#leather', '#lekki', '#craftsmanship', '#travelbag'],
    price: 95000,
    stock: 2,
    shipFrom: 'Lagos (Lekki / VI)',
    likesCount: 289,
    commentsCount: 31,
    sharesCount: 22,
    savesCount: 76,
    viewsCount: 2400,
    watchTimeSeconds: 320,
    isLiked: true,
    isSaved: true,
    createdAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(), // 14h ago
  },
  {
    id: 'post_03',
    sellerId: SELLER_CHIDERA.id,
    seller: SELLER_CHIDERA,
    media: [
      {
        id: 'med_03_a',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1080&auto=format&fit=crop&q=80',
        aspectRatio: 'vertical',
      },
    ],
    caption: 'Natural uncut green Tourmaline mined in Jos, set into solid textured 18k gold band. Unique custom piece.',
    hashtags: ['#jewelry', '#jos', '#tourmaline', '#goldring'],
    price: 145000,
    stock: 1,
    shipFrom: 'Plateau (Jos)',
    likesCount: 88,
    commentsCount: 8,
    sharesCount: 5,
    savesCount: 29,
    viewsCount: 890,
    watchTimeSeconds: 95,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(), // 26h ago
  },
  {
    id: 'post_04',
    sellerId: INITIAL_CURRENT_USER.id,
    seller: INITIAL_CURRENT_USER,
    media: [
      {
        id: 'med_04_a',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=1080&auto=format&fit=crop&q=80',
        aspectRatio: 'vertical',
      },
    ],
    caption: 'Behind the scenes at our Abuja studio: choosing hand-woven textiles for the upcoming harmattan drop. No price, just the art.',
    hashtags: ['#abujafashion', '#behindthescenes', '#textiles'],
    // Social post: NO PRICE
    likesCount: 210,
    commentsCount: 14,
    sharesCount: 18,
    savesCount: 12,
    viewsCount: 1650,
    watchTimeSeconds: 210,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_OFFICIAL_NOTICE: OfficialNotice = {
  id: 'notice_launch',
  title: 'Welcome to Abihani',
  message: 'Nigeria’s direct social marketplace. Buy directly from authentic creators with zero intermediaries.',
  ctaLabel: 'Learn how it works',
  ctaLink: 'terms',
  createdAt: new Date().toISOString(),
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_1001',
    orderNumber: 'AH-84920',
    postId: INITIAL_POSTS[0].id,
    post: INITIAL_POSTS[0],
    buyerId: INITIAL_CURRENT_USER.id,
    buyer: INITIAL_CURRENT_USER,
    sellerId: SELLER_AMINA.id,
    seller: SELLER_AMINA,
    amount: 68000,
    status: 'Paid (Receipt Uploaded)',
    settlementMethod: 'manual',
    buyerNote: 'Please deliver to Wuse II, Abuja. Call before arriving.',
    contactPhone: '+2348031112233',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    messages: [
      {
        id: 'msg_01',
        orderId: 'ord_1001',
        senderId: INITIAL_CURRENT_USER.id,
        senderName: INITIAL_CURRENT_USER.displayName,
        text: 'Hello Amina! I have transferred the ₦68,000 to your Kuda account.',
        createdAt: new Date(Date.now() - 3600 * 1000).toISOString(),
      },
      {
        id: 'msg_02',
        orderId: 'ord_1001',
        senderId: INITIAL_CURRENT_USER.id,
        senderName: INITIAL_CURRENT_USER.displayName,
        text: 'Here is the bank transfer receipt for verification.',
        attachmentUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
        isReceipt: true,
        createdAt: new Date(Date.now() - 3500 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 3600 * 1000).toISOString(),
    hasUnreadBuyer: false,
    hasUnreadSeller: true,
  },
  {
    id: 'ord_1002',
    orderNumber: 'AH-71829',
    postId: INITIAL_POSTS[1].id,
    post: INITIAL_POSTS[1],
    buyerId: INITIAL_CURRENT_USER.id,
    buyer: INITIAL_CURRENT_USER,
    sellerId: SELLER_FEMI.id,
    seller: SELLER_FEMI,
    amount: 95000,
    status: 'Shipped',
    settlementMethod: 'manual',
    buyerNote: 'Deliver to Lekki Phase 1',
    contactPhone: '+2348031112233',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    messages: [
      {
        id: 'msg_f1',
        orderId: 'ord_1002',
        senderId: INITIAL_CURRENT_USER.id,
        senderName: INITIAL_CURRENT_USER.displayName,
        text: 'Paid! Can you send via GIG Logistics?',
        createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
      {
        id: 'msg_f2',
        orderId: 'ord_1002',
        senderId: SELLER_FEMI.id,
        senderName: SELLER_FEMI.displayName,
        text: 'Payment confirmed in GTB. Dropped at GIG today. Tracking number: GIG-88291.',
        createdAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    shippedAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    estimatedDeliveryCountdownHours: 42,
    hasUnreadBuyer: true,
  },
];

export const INITIAL_COMMENTS: Record<string, CommentItem[]> = {
  post_01: [
    {
      id: 'c_01',
      postId: 'post_01',
      user: SELLER_FEMI,
      text: 'Exquisite stitching on the neck embroidery Amina! 🔥',
      createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      likesCount: 4,
    },
    {
      id: 'c_02',
      postId: 'post_01',
      user: INITIAL_CURRENT_USER,
      text: 'Do you have this in midnight blue or navy?',
      createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      likesCount: 1,
    },
  ],
};
